package com.audit_service.repository;

import com.audit_service.model.Address;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface AddressRepository extends JpaRepository<Address, Long> {

    String VALIDATE_STANDARD_PAYMENT_PRODUCT_QUERY = """
SELECT CASE
         WHEN COUNT(*) > 0 THEN 'TRUE'
         ELSE 'FALSE'
       END AS PAYMENT_EXISTS
FROM ATISADMIN.IPA_PAYMENT A,
     ATISADMIN.IPA_ISSUE B,
     STATICDATA.IPA_CONTACT_DET C,
     ATISADMIN.TAGNCYTRADE D,
     ATISADMIN.TAGNTRD_SETTLEMENT E,
     STATICDATA.CCLIENT_CONT_STDPAY P,
     STATICDATA.CCLIENT_CONT_ROLE R
WHERE A.ISSUE_ID = B.ISSUE_ID
  AND A.ATRD_REFNO = D.ATRD_REFNO
  AND B.ISSUE_ID = D.ISSUE_ID
  AND D.ATRD_REFNO = E.ATRD_REFNO
  AND B.ISSUE_ID = C.ISSUE_ID
  AND P.ROLE_NO = C.ROLE_NO
  AND C.ROLE_NO = R.ROLE_NO
  AND P.ROLE_NO = R.ROLE_NO
  AND R.ROLE_CODE = 'ISSUER_PROGRAM'
  AND D.ATRD_TYP_CODE = P.PRD_TYP_CODE
  AND E.CCYCODE = P.PAY_CCY
  AND P.ROLE_NO = :roleNo
  AND P.PAY_CCY = :currency
  AND P.PRD_TYP_CODE = :productType
  AND A.STATUS IN ('AUTH','UNAU')
""";

    String VALIDATE_STANDARD_PAYMENT_ALL_QUERY = """
SELECT CASE
         WHEN COUNT(*) > 0 THEN 'TRUE'
         ELSE 'FALSE'
       END AS PAYMENT_EXISTS
FROM ATISADMIN.IPA_PAYMENT A,
     ATISADMIN.IPA_ISSUE B,
     STATICDATA.IPA_CONTACT_DET C,
     ATISADMIN.TAGNCYTRADE D,
     ATISADMIN.TAGNTRD_SETTLEMENT E,
     STATICDATA.CCLIENT_CONT_STDPAY P,
     STATICDATA.CCLIENT_CONT_ROLE R
WHERE A.ISSUE_ID = B.ISSUE_ID
  AND A.ATRD_REFNO = D.ATRD_REFNO
  AND B.ISSUE_ID = D.ISSUE_ID
  AND D.ATRD_REFNO = E.ATRD_REFNO
  AND B.ISSUE_ID = C.ISSUE_ID
  AND P.ROLE_NO = C.ROLE_NO
  AND P.ROLE_NO = R.ROLE_NO
  AND C.ROLE_NO = R.ROLE_NO
  AND R.ROLE_CODE = 'ISSUER_PROGRAM'
  AND D.ATRD_TYP_CODE IN ('ECP','MTN')
  AND E.CCYCODE = P.PAY_CCY
  AND P.ROLE_NO = :roleNo
  AND P.PAY_CCY = :currency
  AND P.PRD_TYP_CODE = :productType
  AND A.STATUS IN ('AUTH','UNAU')
""";

    List<Address> findByCountry(String country);

    List<Address> findByPostalCode(String postalCode);
}
